apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app : app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-web-app
  templates:
    metadata:
      name: pythonapp
      labels:
        app: python-web-app
    spec:
      containers:
        - name: mypythonapp
          image: mechai/pythoncicd:14
          ports:
           - containerPort: 5000   